jobs:
- name: report-federalist-changes
  plan:
  - aggregate:
    - get: compliance-check-cron
      trigger: true
    - get: report-federalist
  - task: screenshot-cloudtrail
    tags: [iaas]
    file: report-federalist/screenshot-cloudtrail.yml
    params:
      BUCKET: {{federalist-bucket}}
  - task: convert-to-gif
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: asciinema/asciicast2gif
      inputs:
        - name: recording
      outputs:
        - name: gif-recording
      run:
        path: sh
        args:
        - -e
        - -x
        - -c
        - /app/asciicast2gif -s .5 recording/federalist-report.json gif-recording/federalist-report.gif
  - task: curl-to-slack
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: 18fgsa/concourse-task
      inputs:
        - name: gif-recording
      params:
        SLACK_TOKEN: {{slack-token}}
        SLACK_CHANNELS: {{slack-channels}}
      run:
        path: sh
        args:
        - -e
        - -x
        - -c
        - curl -F file=@gif-recording/federalist-report.gif -F channels=${SLACK_CHANNELS} -F token=${SLACK_TOKEN} https://slack.com/api/files.upload

resources:
- name: report-federalist
  type: git
  source:
    uri: {{report-federalist-git-url}}
    branch: {{report-federalist-git-branch}}

- name: compliance-check-cron
  type: cron-resource
  source:
    expression: 0 15 * * 5 # Run at 3PM EST on Friday
    location: "America/New_York"

resource_types:
- name: cron-resource
  type: docker-image
  source:
    repository: cftoolsmiths/cron-resource
